# Generated by Django 4.2.7 on 2025-03-04 06:56

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('balance', models.FloatField(help_text='Current balance from DPDC in Taka')),
                ('hourly_usage', models.FloatField(default=0, help_text='Calculated usage based on balance difference')),
                ('original_balance', models.FloatField(blank=True, help_text='Original balance before calculations', null=True)),
                ('account_id', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Balance Entry',
                'verbose_name_plural': 'Balance Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='electricity_timesta_ee76a1_idx'), models.Index(fields=['balance'], name='electricity_balance_72e228_idx')],
            },
        ),
    ]
